---
  accounts:
    #Wallet APP
    WalletEnable: true
    Walleturl: 'http://192.168.64.1:3000/'

    #Generic Config
    multiAccount: false
    Account: [{
      id: '48865012-47a6-4a31-b082-af84e7150988',
      name: 'notebook_regi',
      Browser: 'firefox'
    }]






  

  multiaccount:
    waitcycles: 4
  # Ativar caso precise de proxy para comunicar o Telegram
  proxy:
    enable: True
    # Proxy IP
    server: 'http://10.255.21.19:128'

  # Time intervals configuration
  time_intervals:
    # Time interval for check if there are available heroes to work
    # Default value (in minutes): 10
    send_heroes_for_work: 3

    # Time interval to update heroes position in the map,
    # Default value (in minutes): 3
    refresh_heroes_positions: 5

    # Time interval to check for login request
    # Default value (in minutes): 5
    check_for_login: 3

    # Time interval to detect freeze in some screen
    # Default value (in minutes): 5
    check_freeze: 5

    # Time interval between moviments
    # Default value (in seconds): 1
    interval_between_moviments: 1

    # Time interval between check qnty of BCoins in chest
    # Default value (in seconds): 30
    interval_between_bcoins_chest: 30

  # How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  threshold:
    # Default value: 0.7
    default: 0.7

    # Default value: 0.8
    commom: 0.8

    # Default value: 0.8
    select_wallet_buttons: 0.8

    # Default value: 0.90
    go_to_work_btn: 0.90

    # Default value: 0.9
    green_bar: 0.9

  # Default value: 60
  scroll_size: 60

  # Default value: 3
  scroll_attemps: 3

  # Default value: true
  use_click_and_drag_instead_of_scroll: true

  # Default value: 200
  click_and_drag_amount: 200

  # Default value: green
  # Available options:
  # all   = select all heroes (regardless of the stamina bar)
  # green = select the heroes with green stamina bar (half or full)
  # full  = select only the heroes with full stamina bar
  select_heroes_mode: "green"

  # Telegram bot config
  telegram:
    enabled: True
    token: '5034165231:AAF0zUU8KZrJK8o4KkF0KDoxIJnIJptrOnA'
    token_brave: '5034165231:AAF0zUU8KZrJK8o4KkF0KDoxIJnIJptrOnA' #NFT2
    token_firefox: '5051279188:AAEqq_nqWHD0JmDOSodi2Ag8qm7OBLh2nEU' #NFT0
    token_chrome: '5069299084:AAHU9Jqn9NOUlPuw-IDPRTtmBkfwCGFT2C8' #NFT1
    chat_id: '729522981'
    chat_id_2: '766192347'
  discord:
    enabled: True
    token: 'OTI2NTkzNDgyNjI0MjA4OTk2.Yc97bQ.W2vNMeGwU4X1HBX82kDrRAj6Vms'
    channel: 926549197774266438